version: 2.1
orbs:
  slack: circleci/slack@3.4.2
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
  staging_deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - deploy:
          name: Staging Deployment
          command: |
            echo 'DEPLOYING STAG!!!'
workflows:
  simple_workflow:
    jobs:
      - build
      - test
      - slack/approval-notification:
          message: Pending approval
          webhook: https://hooks.slack.com/services/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
      - wait_for_approve:
          type: approval
          requires:
            - build
      - staging_deploy:
          requires:
            - wait_for_approve