version: 2
jobs:
  one:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - run: echo "A first hello"
      - run: echo "test" |cat  >> test.txt
       
  two:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - run: echo "A more familiar hi"  
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two:
          requires:
            - one
