version: 2.1

parameters:
  timestamp:
    type: string
    default: $(date +%s)
  git-author:
    type: string
    default: $(git log --format='%aN' ${CIRCLE_SHA1}^!)
  deployer:
    type: string
    default: $(git config user.name)
  commit-link:
    type: string
    default: "https://github.com/procurify/procurifydevelopment/commits"
  
  

executors:
  python-executor:
    docker:
      - image: circleci/python:3.8
aliases:
  - &ola
    run:
      name: say ola
      command: |
        echo "Ola!a"

orbs:
  slack: circleci/slack@3.4.2
  testimio: testimio/runner@1.1.0

jobs:
  build:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            if ["${CIRCLE_BRANCH}" == "master"];
            then
              echo 'Hello World!'8
            else
              echo 'This is the delivery pipeline'
            fi
            git log --format='%aN' ${CIRCLE_SHA1}^!
      - slack/notify:
          color: '#42e2f4'
          title: Starting Deployment 
          author_name: $(git log --format='%aN' ${CIRCLE_SHA1}^!)
          author_link: "https://github.com/procurify/procurifydevelopment/commits/${CIRCLE_SHA1}"
          include_project_field: false
          ts:  <<pipeline.parameters.timestamp>>
          message:
            "*Production Deployment*: \ncommit ${CIRCLE_SHA1} by $(git config user.name)"
          webhook: ${SLACK_WEBHOOK}
  staging_deploy:
    executor: python-executor
    steps:
      - deploy:
          name: Staging Deployment
          command: |
            echo 'DEPLOYING STAG!!!'

workflows:
  simple_workflow:
    jobs:
      - build
      - staging_deploy
      - testimio/run_tests:
          token: ${TESTIM_TOKEN}
          project_id: ${TESTIMPROJECT_ID}
          grid_name: 'Testim-Grid'
          options:  |
            ' "Regression:Navigation"'

      - slack/approval-notification:
          requires:
            - build
          message: Waiting Approval on $(git config user.name)
          include_project_field: false                   
          webhook: ${SLACK_WEBHOOK_CIRCLE}
      - wait_for_approve:
          type: approval
          requires:
            - testimio/run_tests
      - staging_deploy:
          requires:
            - wait_for_approve