# Orb 'circleci/slack@3.4.2' resolved to 'circleci/slack@3.4.2'
# Orb 'testimio/runner@1.1.0' resolved to 'testimio/runner@1.1.0'
version: 2
jobs:
  staging_deploy:
    docker:
    - image: circleci/python:3.8
    steps:
    - checkout
    - run:
        name: get slack id
        command: |
          AUTHOR_EMAIL=$(git log -n1 --format='%ae' $CIRCLE_SHA1)
          LOOKUP_RESULT=$(curl -s "${SLACK_API_URL}/users.lookupByEmail?token=${SLACK_BOT_TOKEN}&email=${AUTHOR_EMAIL}")
          SUCCESS=$(echo "$LOOKUP_RESULT" | jq ".ok")
          if [[ "$SUCCESS" == "true" ]]; then
            USER_ID=$(echo "$LOOKUP_RESULT" | jq -r ".user.id")
            CHANNEL=$USER_ID
            NAME=$(echo "$LOOKUP_RESULT" | jq -r ".user.name")
            echo "export MENTIONS=${USER_ID}" >> $BASH_ENV
          fi
    - run:
        command: |
          if [ ! -x /bin/bash ]; then
            echo Bash not installed.
            exit 1
          fi
        name: Provide error if non-bash shell
    - run:
        command: |
          # Provide error if no webhook is set and error. Otherwise continue
          if [ -z "${SLACK_WEBHOOK}" ]; then
            echo "NO SLACK WEBHOOK SET"
            echo "Please input your SLACK_WEBHOOK value either in the settings for this project, or as a parameter for this orb."
            exit 1
          else
            #Create Members string
            if [ -n "${MENTIONS},U0286CK1D" ]; then
              IFS="," read -ra SLACK_MEMBERS <<< "${MENTIONS},U0286CK1D"
              for i in "${SLACK_MEMBERS[@]}"; do
                if [ $(echo ${i} | head -c 1) == "S" ]; then
                  SLACK_MENTIONS="${SLACK_MENTIONS}<!subteam^${i}> "
                elif echo ${i} | grep -E "^(here|channel|everyone)$" > /dev/null; then
                  SLACK_MENTIONS="${SLACK_MENTIONS}<!${i}> "
                else
                  SLACK_MENTIONS="${SLACK_MENTIONS}<@${i}> "
                fi
              done
            fi

            curl -X POST -H 'Content-type: application/json' \
              --data \
              "{ \
                \"attachments\": [ \
                  { \
                    \"fallback\": \"Pending approval - https://circleci.com/workflow-run/${CIRCLE_WORKFLOW_ID}\", \
                    \"text\": \"Pending approval $SLACK_MENTIONS\", \
                    \"fields\": [ \
                      { \
                        \"title\": \"Project\", \
                        \"value\": \"$CIRCLE_PROJECT_REPONAME\", \
                        \"short\": true \
                      }, \
                      { \
                        \"title\": \"Job Number\", \
                        \"value\": \"$CIRCLE_BUILD_NUM\", \
                        \"short\": true \
                      } \
                    ], \
                    \"actions\": [ \
                      { \
                        \"type\": \"button\", \
                        \"text\": \"Visit Workflow\", \
                        \"url\": \"https://circleci.com/workflow-run/${CIRCLE_WORKFLOW_ID}\" \
                      } \
                    ], \
                    \"color\": \"#3AA3E3\" \
                  } \
                ] \
              }" ${SLACK_WEBHOOK}
            echo "Awaiting approval notified."
          fi
        name: Slack - Sending Approval Notification
        shell: /bin/bash
  slack/approval-notification:
    docker:
    - environment:
        TERM: dumb
      image: cibuilds/base:latest
    resource_class: small
    steps:
    - run:
        command: |
          if [ ! -x /bin/bash ]; then
            echo Bash not installed.
            exit 1
          fi
        name: Provide error if non-bash shell
    - run:
        command: "# Provide error if no webhook is set and error. Otherwise continue\nif [ -z \"${SLACK_WEBHOOK}\" ]; then\n  echo \"NO SLACK WEBHOOK SET\"\n  echo \"Please input your SLACK_WEBHOOK value either in the settings for this project, or as a parameter for this orb.\"\n  exit 1\nelse\n  #Create Members string\n  if [ -n \"${MENTIONS}\" ]; then\n    IFS=\",\" read -ra SLACK_MEMBERS <<< \"${MENTIONS}\"\n    for i in \"${SLACK_MEMBERS[@]}\"; do\n      if [ $(echo ${i} | head -c 1) == \"S\" ]; then\n        SLACK_MENTIONS=\"${SLACK_MENTIONS}<!subteam^${i}> \"\n      elif echo ${i} | grep -E \"^(here|channel|everyone)$\" > /dev/null; then\n        SLACK_MENTIONS=\"${SLACK_MENTIONS}<!${i}> \"\n      else\n        SLACK_MENTIONS=\"${SLACK_MENTIONS}<@${i}> \"\n      fi\n    done\n  fi\n\n  curl -X POST -H 'Content-type: application/json' \\\n    --data \\\n    \"{ \\\n      \\\"attachments\\\": [ \\\n        { \\\n          \\\"fallback\\\": \\\"*This Deployment is waiting for approval from*: \n ${CIRCLE_USERNAME}\n *Commit ID* :\n <https://github.com/procurify/procurifydevelopment/commits/${CIRCLE_SHA1}|${CIRCLE_SHA1}> \n  - https://circleci.com/workflow-run/${CIRCLE_WORKFLOW_ID}\\\", \\\n          \\\"text\\\": \\\"*This Deployment is waiting for approval from*: \n ${CIRCLE_USERNAME}\n *Commit ID* :\n <https://github.com/procurify/procurifydevelopment/commits/${CIRCLE_SHA1}|${CIRCLE_SHA1}> \n  $SLACK_MENTIONS\\\", \\\n          \\\"fields\\\": [ \\\n            { \\\n              \\\"title\\\": \\\"Job Number\\\", \\\n              \\\"value\\\": \\\"$CIRCLE_BUILD_NUM\\\", \\\n              \\\"short\\\": true \\\n            } \\\n          ], \\\n          \\\"actions\\\": [ \\\n            { \\\n              \\\"type\\\": \\\"button\\\", \\\n              \\\"text\\\": \\\"Visit Workflow\\\", \\\n              \\\"url\\\": \\\"https://circleci.com/workflow-run/${CIRCLE_WORKFLOW_ID}\\\" \\\n            } \\\n          ], \\\n          \\\"color\\\": \\\"#3AA3E3\\\" \\\n        } \\\n      ] \\\n    }\" ${SLACK_WEBHOOK}\n  echo \"Awaiting approval notified.\"\nfi\n"
        name: Slack - Sending Approval Notification
        shell: /bin/bash
  build:
    docker:
    - image: circleci/python:3.8
    steps:
    - checkout
    - run:
        name: The First Step
        command: |
          if ["${CIRCLE_BRANCH}" == "master"];
          then
            echo 'Hello World!'8
          else
            echo 'This is the delivery pipeline'
          fi
          git log --format='%aN' ${CIRCLE_SHA1}^!
    - run:
        command: |
          if [ ! -x /bin/bash ]; then
            echo Bash not installed.
            exit 1
          fi
        name: Provide error if non-bash shell
    - run:
        command: "# Provide error if no webhook is set and error. Otherwise continue\nif [ -z \"${SLACK_WEBHOOK}\" ]; then\n  echo \"NO SLACK WEBHOOK SET\"\n  echo \"Please input your SLACK_WEBHOOK value either in the settings for this project, or as a parameter for this orb.\"\n  exit 1\nelse\n  # Webhook properly set.\n  echo Notifying Slack Channel\n  #Create Members string\n  if [ -n \"\" ]; then\n    IFS=\",\" read -ra SLACK_MEMBERS <<< \"\"\n    for i in \"${SLACK_MEMBERS[@]}\"; do\n      if [ $(echo ${i} | head -c 1) == \"S\" ]; then\n        SLACK_MENTIONS=\"${SLACK_MENTIONS}<!subteam^${i}> \"\n      elif echo ${i} | grep -E \"^(here|channel|everyone)$\" > /dev/null; then\n        SLACK_MENTIONS=\"${SLACK_MENTIONS}<!${i}> \"\n      else\n        SLACK_MENTIONS=\"${SLACK_MENTIONS}<@${i}> \"\n      fi\n    done\n  fi\n  curl -X POST -H 'Content-type: application/json' \\\n    --data \\\n    \"{ \\\n      \\\"attachments\\\": [ \\\n        { \\\n          \\\"fallback\\\": \\\"*Commit ID* :\n <https://github.com/procurify/procurifydevelopment/commits/${CIRCLE_SHA1}|${CIRCLE_SHA1}> \n *By*:\n ${CIRCLE_USERNAME} - $CIRCLE_BUILD_URL\\\", \\\n          \\\"text\\\": \\\"*Commit ID* :\n <https://github.com/procurify/procurifydevelopment/commits/${CIRCLE_SHA1}|${CIRCLE_SHA1}> \n *By*:\n ${CIRCLE_USERNAME} $SLACK_MENTIONS\\\", \\\n          \\\"author_name\\\": \\\"\\\", \\\n          \\\"author_link\\\": \\\"\\\", \\\n          \\\"title\\\": \\\"Deployment Started\\\", \\\n          \\\"title_link\\\": \\\"https://github.com/procurify/procurifydevelopment/commits/${CIRCLE_SHA1}\\\", \\\n          \\\"footer\\\": \\\"\\\", \\\n          \\\"ts\\\": \\\"$(date +%s)\\\", \\\n          \\\"fields\\\": [ \\\n            { \\\n              \\\"title\\\": \\\"Job Number\\\", \\\n              \\\"value\\\": \\\"$CIRCLE_BUILD_NUM\\\", \\\n              \\\"short\\\": true \\\n            } \\\n          ], \\\n          \\\"image_url\\\": \\\"\\\", \\\n          \\\"actions\\\": [ \\\n            { \\\n              \\\"type\\\": \\\"button\\\", \\\n              \\\"text\\\": \\\"Visit Job\\\", \\\n              \\\"url\\\": \\\"$CIRCLE_BUILD_URL\\\" \\\n            } \\\n          ], \\\n          \\\"color\\\": \\\"#0098a6\\\" \\\n        } \\\n      ] \\\n    }\" ${SLACK_WEBHOOK}\nfi\n"
        name: Slack Notification
        shell: /bin/bash
workflows:
  simple_workflow:
    jobs:
    - staging_deploy
    - slack/approval-notification:
        requires:
        - staging_deploy
    - wait_for_approve:
        type: approval
    - build
  version: 2

# Original config.yml file:
# version: 2.1
# 
# parameters:
#   timestamp:
#     type: string
#     default: $(date +%s)
#   git-author:
#     type: string
#     default: $(git log --format='%aN' ${CIRCLE_SHA1}^!)
#   deployer:
#     type: string
#     default: $(git config user.name)
#   SLACK-API-URL:
#     type: string
#     default: \"https://slack.com/api\"
#   
#   
# 
# executors:
#   python-executor:
#     docker:
#       - image: circleci/python:3.8
# aliases:
#   - &ola
#     run:
#       name: say ola
#       command: |
#         echo \"Ola!a\"
# 
# orbs:
#   slack: circleci/slack@3.4.2
#   testimio: testimio/runner@1.1.0
# 
# jobs:
#   build:
#     executor: python-executor
#     steps:
#       - checkout
#       - run:
#           name: The First Step
#           command: |
#             if [\"${CIRCLE_BRANCH}\" == \"master\"];
#             then
#               echo 'Hello World!'8
#             else
#               echo 'This is the delivery pipeline'
#             fi
#             git log --format='%aN' ${CIRCLE_SHA1}^!
#       - slack/notify:
#           color: '#0098a6'
#           title: \"Deployment Started\"
#           title_link: https://github.com/procurify/procurifydevelopment/commits/${CIRCLE_SHA1}
#           include_project_field: false
#           ts:  <<pipeline.parameters.timestamp>>
#           message:
#             \"*Commit ID* :\\n
#             <https://github.com/procurify/procurifydevelopment/commits/${CIRCLE_SHA1}|${CIRCLE_SHA1}> \\n
#             *By*:\\n ${CIRCLE_USERNAME}\"
# 
#           webhook: ${SLACK_WEBHOOK}
#   staging_deploy:
#     executor: python-executor
#     steps:
#       - checkout
#       - run:  
#           name: get slack id
#           command: |
#             AUTHOR_EMAIL=$(git log -n1 --format='%ae' $CIRCLE_SHA1)
#             LOOKUP_RESULT=$(curl -s \"${SLACK_API_URL}/users.lookupByEmail?token=${SLACK_BOT_TOKEN}&email=${AUTHOR_EMAIL}\")
#             SUCCESS=$(echo \"$LOOKUP_RESULT\" | jq \".ok\")
#             if [[ \"$SUCCESS\" == \"true\" ]]; then
#               USER_ID=$(echo \"$LOOKUP_RESULT\" | jq -r \".user.id\")
#               CHANNEL=$USER_ID
#               NAME=$(echo \"$LOOKUP_RESULT\" | jq -r \".user.name\")
#               echo \"export MENTIONS=${USER_ID}\" >> $BASH_ENV
#             fi
#       - slack/approval:
#           message: Pending approval
#           mentions: '${MENTIONS},U0286CK1D'
#           webhook: ${SLACK_WEBHOOK}
# workflows:
#   simple_workflow:
#     jobs:
#       - staging_deploy
#       - slack/approval-notification:
#           requires:
#             - staging_deploy
#           mentions: ${MENTIONS}
#           message: \"*This Deployment is waiting for approval from*: \\n
#               ${CIRCLE_USERNAME}\\n
#              *Commit ID* :\\n
#             <https://github.com/procurify/procurifydevelopment/commits/${CIRCLE_SHA1}|${CIRCLE_SHA1}> \\n
#               \"
#           include_project_field: false                   
#           webhook: ${SLACK_WEBHOOK}
#       - wait_for_approve:
#           type: approval
#       - build
#           