version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.8
aliases:
  - &ola
    run:
      name: say ola
      command: |
        echo "Ola!a"

orbs:
  slack: circleci/slack@3.4.2
  testimio: testimio/runner@1.1.0

jobs:
  build:
    executor: python-executor
    steps:
      - run:
          name: The First Step
          command: |
            if ["${CIRCLE_BRANCH}" == "master"];
            then
              echo 'Hello World!'8
            else
              echo 'This is the delivery pipeline'
            fi
      - slack/notify:
          color: '#42e2f4'
          title: Deployment Complete
          title_link: 'Commit ID: 123123123'
          ts: $(date +%s)
          message:
            " This is unquoted text\n>This is quoted text\n>This is still quoted text\nThis is unquoted text again"
          footer: 
          webhook: ${SLACK_WEBHOOK}
  staging_deploy:
    executor: python-executor
    steps:
      - deploy:
          name: Staging Deployment
          command: |
            echo 'DEPLOYING STAG!!!'

workflows:
  simple_workflow:
    jobs:
      - build
      - staging_deploy
      - testimio/run_tests:
          token: ${TESTIM_TOKEN}
          project_id: ${TESTIMPROJECT_ID}
          grid_name: 'Testim-Grid'
          options:  |
            ' --test-plan "Regression:AP" --test-plan "Regression:ApprovalRouting" --test-plan "Regression:Finance" \
            --test-plan "Regression:Request" --test-plan "Regression:Approval" --test-plan "Regression:LocationsAndUsers" \
            --test-plan "Regression:Procure" --test-plan "Regression:Receive" --test-plan "Regression:Navigation" \
            --base-url https://release.procurify.com'
          filters:
            branches:
              only:
                - beta

      - slack/approval-notification:
          requires:
            - build
          message: Waiting Approval                    
          webhook: ${SLACK_WEBHOOK_CIRCLE}
      - wait_for_approve:
          type: approval
          requires:
            - testimio/run_tests
      - staging_deploy:
          requires:
            - wait_for_approve