version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.8
aliases:
  - &ola
    run:
      name: say ola
      command: |
        echo "Ola!a"
orbs:
  slack: circleci/slack@3.4.2
  testimio: testimio/runner@1.1.0

jobs:
  build:
    executor: python-executor
    steps:
      - run:
          name: The First Step
          command: |
            if [${CIRCLE_BRANCH} == "master"];
              echo 'Hello World!'8
            else
              echo 'This is the delivery pipeline'
            fi
      - slack/notify:
          color: '#42e2f4'
          message: This is a custom message notification
          webhook: ${SLACK_WEBHOOK}
  staging_deploy:
    executor: python-executor
    steps:
      - deploy:
          name: Staging Deployment
          command: |
            echo 'DEPLOYING STAG!!!'

workflows:
  simple_workflow:
    jobs:
      - build
      - staging_deploy
      - testimio/run_tests:
          token: ${TESTIM_TOKEN}
          project_id: ${TESTIMPROJECT_ID}
          grid_name: 'Testim-Grid'
          options: '--test-plan "Regression:AP" --test-plan "Regression:Receive"  
          --test-plan "Regression:LocationsAndUsers"'
      - slack/approval-notification:
          requires:
            - build
          message: Pending approval
          webhook: ${SLACK_WEBHOOK_CIRCLE}
      - wait_for_approve:
          type: approval
          requires:
            - testimio/run_tests
      - staging_deploy:
          requires:
            - wait_for_approve