version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.8
aliases:
  - &ola:
    run: say ola
    command:  |
      echo 'Ola!'
orbs:
  slack: circleci/slack@3.4.2
jobs:
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - *ola
  test:
    executor: python-executor
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - *ola
      - slack/notify:
          color: '#42e2f4'
          message: This is a custom message notification
          webhook: https://hooks.slack.com/services/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
  staging_deploy:
    executor: python-executor
    steps:
      - deploy:
          name: Staging Deployment
          command: |
            echo 'DEPLOYING STAG!!!'
      - *ola
workflows:
  simple_workflow:
    jobs:
      - build
      - test
      - slack/approval-notification:
          message: Pending approval
          webhook: https://hooks.slack.com/services/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
      - wait_for_approve:
          type: approval
          requires:
            - build
      - staging_deploy:
          requires:
            - wait_for_approve